- name: disable default nodejs 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop system user 
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue code
    ansible.builtin.get:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
# This module thinks file exist on ansible control server, needs to extract on to remote machine.
# remote_src: yes means file already exist in catalogue server
  - name: extract catalogue code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

# install dependecies
  - name: Install dependencies
    community.general.npm:
      path: /app
  
  - name: copy catalogue service to system directory
    ansible.duiltin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: systemctl demon reload
    ansible.builtin.systemd_servie:
      demon_reload: true


  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: staerted
      enabled: yes

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: load products data
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output


  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0
   