- name: app account setup
  include_role:
    name: common
    tasks_from: app-setup


- name: maven set uo
  include_role:
    name: common
    tasks_from: maven

- name: import data
  community.mysql.mysql_db:
    name: all
    login_user: "{{ my sql root user }}"
    login_password: "{{ my sql root pass }}"
    login_host: "{{ MYSQL_HOST }}"
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql


- name: maven set uo
  include_role:
    name: common
    tasks_from: systemd
