- name: app account setup
  include_role:
    name: common
    tasks_from: app-setup

- name: node js setup
  include_role:
    name: common
    tasks_from: nodejs-setup



- name: systemd setup
  include_role:
    name: common
    tasks_from: systemdaemon-setup
  