- name: app account setup
  include_role:
    name: common
    tasks_from: app-setup


- name: python setup
  include_role:
    name: common
    tasks_from: python




- name:systemd set up
  include_role:
    name: common
    tasks_from: systemd
