- name: copy {{ component }} service to system directory
  ansible.duiltin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/catalogue.service

- name: systemctl demon reload
  ansible.builtin.systemd_servie:
    demon_reload: true


- name: start and enable {{ component }}
  ansible.builtin.service:
    name: {{ component }}
    state: restarted
    enabled: yes