- name: copy catalogue service to system directory
  ansible.duiltin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: systemctl demon reload
  ansible.builtin.systemd_servie:
    demon_reload: true


- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes